# Generated by Django 4.0.3 on 2022-03-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_codes/'),
        ),
    ]
