# Generated by Django 4.0.3 on 2022-03-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='longitude',
            new_name='long',
        ),
    ]
