# Generated by Django 4.0.3 on 2022-03-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_rename_long_point_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
    ]
