# Generated by Django 4.0.3 on 2022-03-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_alter_point_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.CharField(max_length=255, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lng',
            field=models.CharField(max_length=255, verbose_name='Долгота'),
        ),
    ]
