# Generated by Django 4.0.3 on 2022-03-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_alter_point_address_alter_point_lat_alter_point_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
